name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/REPO_NAME.git
          git fetch upstream

      - name: Merge Upstream
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push to Fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} main
